apiVersion: v1
kind: Service
metadata:
  name: nishu
  namespace: ty
spec:
  selector:
    app.kubernetes.io/name: nishu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: Load Balancer